services:
    web:
        platform: linux/amd64 # Explicitly set for TDX
        image: pivortex/shade-agent-template:latest@sha256:55507ecdf3caf57b49ccc9c50fb01396dd3de606dfefc5202ad54374d5794f51
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
